@Dashboard.API_HostAddress = http://localhost:5185

###

GET {{Dashboard.API_HostAddress}}/api/readings?stationId=backyard-01&limit=20

###

GET {{Dashboard.API_HostAddress}}/api/readings/backyard-01/latest

###

GET {{Dashboard.API_HostAddress}}/api/readings/latest

###

GET {{Dashboard.API_HostAddress}}/api/alerts?stationId=backyard-01&limit=20

###
